name = "ArmaForces NEW_MOD_PRETTY"
prefix = "NEW_MOD_ABBR"
author = "ArmaForces"
files = [
    "LICENSE",
    "mod.cpp",
    "README.md"
]

exclude = ["*.psd", "*.png", "*.tga"]

modname = "armaforces_NEW_MOD_SNAKE"
key_name = "armaforces_NEW_MOD_SNAKE_{{version}}"
authority = "armaforces_NEW_MOD_SNAKE_{{version}}"

releasebuild = [
    "!set_version",
    "@zip",
    "!publish"
]

[header_exts]
version = "{{git \"id 8\"}}"

[scripts.set_version]
    steps_windows = [
        "powershell ./tools/Set-Version.ps1 {{version}} '@armaforces_NEW_MOD_SNAKE'"
    ]
    steps_linux = [
        "sed -i 's/0.0.0/{{version}}/' ./releases/{{version}}/@armaforces_NEW_MOD_SNAKE/mod.cpp"
    ]
    # show_output = true

[scripts.publish]
    steps_windows = [
        "powershell ./tools/Publish.ps1 {{version}} 1934142795 '@armaforces_NEW_MOD_SNAKE'"
    ]
    show_output = true
