#define MAINPREFIX z
#define PREFIX NEW_MOD_ABBR

#include "script_version.hpp"

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCH
#define VERSION_AR  MAJOR,MINOR,PATCH

#define REQUIRED_VERSION 2.14

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(NEW_MOD_ABBR_CAPS - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(NEW_MOD_ABBR_CAPS - COMPONENT)
#endif
